apiVersion: image.openshift.io/v1
generation: 0
image:
  dockerImageLayers: null
  dockerImageMetadata: null
  metadata:
    creationTimestamp: null
kind: ImageStreamTag
lookupPolicy:
  local: false
metadata:
  creationTimestamp: null
  name: psi-exporter:latest
tag:
  annotations: {}
  generation: null
  importPolicy: {}
  name: ""
  referencePolicy:
    type: ""
