apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: psi-exporter
  namespace: openshift-monitoring
spec:
  endpoints:
  - interval: 15s
    port: psi-exporter 
    scheme: http
    relabelings:
    - action: replace
      regex: (.*)
      replacement: $1
      sourceLabels:
      - __meta_kubernetes_pod_node_name
      targetLabel: instance
  jobLabel: app.kubernetes.io/name
  namespaceSelector: {}
  selector:
    matchLabels:
      app.kubernetes.io/name: psi-exporter
